### ISSUE TITLE
Show lock icon on channel

### ISSUE THREAD

**Issue by rollingmoai** [JustOptimize/return-ShowHiddenChannels#34] opened 2022-10-17 10:59 UTC

**Comment by Azurz** [comment] 2022-10-17 11:39
![image](https://user-images.githubusercontent.com/35930914/196167851-e37b66c1-7f80-4e16-84d6-31221b138de9.png)

**Comment by JustOptimize** [comment] 2022-10-19 14:15
Duplicate of #26

**Closed by JustOptimize** 2022-10-19 14:15 UTC
Labels: enhancement
