### ISSUE TITLE
META not found when adding Plugin to folder

### ISSUE THREAD

**Issue by okeo1295** [JustOptimize/return-ShowHiddenChannels#114] opened 2023-03-25 16:33 UTC
Heya!

I get this error (META not found) when I move the plugin to the plugin folder. After I clicked away the error, the plugin is also not shown in the plugin list with my other plugins. I updated to the new BetterDiscord Version and my BetterDiscord Version now is 1.9.1.

![META not found](https://user-images.githubusercontent.com/128922293/227729825-9a00a355-807d-490d-a806-9e275166daca.png)

**Comment by okeo1295** [comment] 2023-03-25 16:34
(i updated to 1.9.1 btw)

**Comment by JustOptimize** [comment] 2023-03-25 17:24
Duplicate of:
- #29 
- #46 
- #108 
- #109 
And many others. Read the readme!

**Closed by JustOptimize** 2023-03-25 17:24 UTC

**Comment by gabriel2631** [comment] 2024-08-06 18:29
nao estou conseguindo colocar meu plug como faço para remover o return
