### ISSUE TITLE
Broken Modules

### ISSUE THREAD

**Issue by KraZ5M** [JustOptimize/return-ShowHiddenChannels#190] opened 2024-06-19 09:56 UTC
Went to load up this morning and it the plugin came up with '(SHC) Broken Modules', and can't see to fix it. 

Can someone help me?

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/115189405/769bbb99-5aa3-4e72-82b4-bd29392fe4b1)

**Comment by JustOptimize** [comment] 2024-06-19 10:11
Dupe of #188

**Closed by JustOptimize** 2024-06-19 10:11 UTC
