### ISSUE TITLE
SHC BROKEN MODULE ERROR

### ISSUE THREAD

**Issue by CookieProgrammer93** [JustOptimize/return-ShowHiddenChannels#191] opened 2024-06-19 14:32 UTC
ShowHiddenChannels has detected that some modules are broken, would you like to start anyway? (This might break the plugin or Discord itself)
Even after replacing it with the plugin updated 2 hours ago still this issue persists. Does it require us to uninstall install discord again?

**Comment by samdebanenman** [comment] 2024-06-19 15:03
duplicate of #188

**Comment by CookieProgrammer93** [comment] 2024-06-19 15:07
> duplicate of #188

but is this issue resolved?

**Comment by CookieProgrammer93** [comment] 2024-06-19 15:08
that duplicate was 14hrs ago and JustOptimize mentioned a new fix file temporary for the plugin yet that plugin is also not working

**Comment by CookieProgrammer93** [comment] 2024-06-19 15:10
This is a duplicate

**Closed** 2024-06-19 15:10 UTC
